# Generated by Django 5.0.7 on 2024-07-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=200)),
                ('imagen_caratula', models.ImageField(upload_to='')),
                ('parrafo_1', models.TextField()),
                ('imagen_1', models.ImageField(upload_to='')),
                ('imagen_2', models.ImageField(upload_to='')),
                ('parrafo_2', models.TextField()),
                ('sintesis', models.TextField()),
                ('nota', models.FloatField()),
                ('aside_generos', models.CharField(max_length=300)),
                ('aside_plataformas', models.CharField(max_length=200)),
                ('aside_creador', models.CharField(max_length=100)),
                ('aside_pais_origen', models.CharField(max_length=100)),
                ('aside_dato_curioso', models.CharField(max_length=500)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
