# Generated by Django 5.0.7 on 2024-07-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resenias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-creado'], 'verbose_name': 'Reseña', 'verbose_name_plural': 'Reseñas'},
        ),
        migrations.AlterField(
            model_name='project',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación: '),
        ),
        migrations.AlterField(
            model_name='project',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación: '),
        ),
        migrations.AlterField(
            model_name='project',
            name='imagen_1',
            field=models.ImageField(upload_to='', verbose_name='imagen 1'),
        ),
        migrations.AlterField(
            model_name='project',
            name='imagen_2',
            field=models.ImageField(upload_to='', verbose_name='segundo parrafo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='imagen_caratula',
            field=models.ImageField(upload_to='', verbose_name='imagen de la caratula'),
        ),
        migrations.AlterField(
            model_name='project',
            name='nota',
            field=models.FloatField(verbose_name='nota'),
        ),
        migrations.AlterField(
            model_name='project',
            name='parrafo_1',
            field=models.TextField(verbose_name='primer parrafo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='parrafo_2',
            field=models.TextField(verbose_name='parrafo 2'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sintesis',
            field=models.TextField(verbose_name='síntesis'),
        ),
        migrations.AlterField(
            model_name='project',
            name='subtitulo',
            field=models.CharField(max_length=200, verbose_name='subtitulo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='título'),
        ),
    ]
