# Generated by Django 5.0.7 on 2024-07-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resenias', '0002_alter_project_options_alter_project_actualizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='imagen_2',
            field=models.ImageField(upload_to='', verbose_name='imagen 2'),
        ),
        migrations.AlterField(
            model_name='project',
            name='parrafo_2',
            field=models.TextField(verbose_name='segundo parrafo'),
        ),
    ]
