# Generated by Django 5.0.7 on 2024-07-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resenias', '0003_alter_project_imagen_2_alter_project_parrafo_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='imagen_caratula',
            field=models.ImageField(upload_to='proyectos/<django.db.models.fields.CharField>', verbose_name='imagen de la caratula'),
        ),
    ]
