# Generated by Django 5.0.7 on 2024-07-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resenias', '0009_alter_project_imagen_1_alter_project_imagen_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='nota',
            field=models.CharField(max_length=10, verbose_name='nota'),
        ),
    ]
