# Generated by Django 5.0.7 on 2024-07-19 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resenias', '0010_alter_project_nota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='subtitulo',
        ),
    ]
