# Generated by Django 5.0.7 on 2024-07-19 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resenias', '0011_remove_project_subtitulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.RemoveField(
            model_name='project',
            name='actualizado',
        ),
        migrations.RemoveField(
            model_name='project',
            name='aside_creador',
        ),
        migrations.RemoveField(
            model_name='project',
            name='aside_dato_curioso',
        ),
        migrations.RemoveField(
            model_name='project',
            name='aside_generos',
        ),
        migrations.RemoveField(
            model_name='project',
            name='aside_pais_origen',
        ),
        migrations.RemoveField(
            model_name='project',
            name='aside_plataformas',
        ),
        migrations.RemoveField(
            model_name='project',
            name='creado',
        ),
        migrations.RemoveField(
            model_name='project',
            name='imagen_1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='imagen_2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='imagen_caratula',
        ),
        migrations.RemoveField(
            model_name='project',
            name='nota',
        ),
        migrations.RemoveField(
            model_name='project',
            name='parrafo_1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='parrafo_2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sintesis',
        ),
        migrations.RemoveField(
            model_name='project',
            name='titulo',
        ),
    ]
