# Generated by Django 5.0.7 on 2024-07-19 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resenias', '0013_alter_project_options_project_actualizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='aside_creador',
            field=models.CharField(default='default', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='aside_dato_curioso',
            field=models.CharField(default='default', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='aside_generos',
            field=models.CharField(default='default', max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='aside_pais_origen',
            field=models.CharField(default='default', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='aside_plataformas',
            field=models.CharField(default='default', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='nota',
            field=models.CharField(default='default', max_length=10, verbose_name='nota'),
        ),
        migrations.AlterField(
            model_name='project',
            name='parrafo_1',
            field=models.TextField(default='default', verbose_name='primer parrafo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='parrafo_2',
            field=models.TextField(default='default', verbose_name='segundo parrafo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sintesis',
            field=models.TextField(default='default', verbose_name='síntesis'),
        ),
        migrations.AlterField(
            model_name='project',
            name='subtitulo_1',
            field=models.CharField(default='default', max_length=200, verbose_name='subtitulo 1'),
        ),
        migrations.AlterField(
            model_name='project',
            name='subtitulo_2',
            field=models.CharField(default='default', max_length=200, verbose_name='subtitulo 2'),
        ),
        migrations.AlterField(
            model_name='project',
            name='titulo',
            field=models.CharField(default='default', max_length=100, verbose_name='título'),
        ),
    ]
