# Generated by Django 5.0.7 on 2024-07-20 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resenias', '0015_alter_project_aside_creador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
